---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint

platforms:
  - name: zabbix-agent-docker-centos
    image: milcom/centos7-systemd:latest
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - docker
    privileged: True
  - name: zabbix-agent-centos
    image: milcom/centos7-systemd:latest
    groups:
      - agent
    privileged: True
  - name: zabbix-agent-fedora
    image: jrei/systemd-fedora:latest
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - agent
    privileged: True
  - name: zabbix-agent-debian-stretch
    image: minimum2scp/systemd-stretch:latest
    command: /sbin/init
    groups:
      - agent
    privileged: True
  - name: zabbix-agent-mint
    image: vcatechnology/linux-mint
    groups:
      - agent
    privileged: True
  - name: zabbix-agent-ubuntu-bionic
    image: solita/ubuntu-systemd:bionic
    groups:
      - agent
    privileged: True

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      all:
        zabbix_agent_server: 192.168.3.33
        zabbix_agent_serveractive: 192.168.3.33
        zabbix_agent_listenip: 0.0.0.0
        zabbix_agent_tlsconnect: psk
        zabbix_agent_tlsaccept: psk
        zabbix_agent_tlspskidentity: my_Identity
        zabbix_agent_tlspskfile: /data/certs/zabbix.psk
        zabbix_agent_tlspsk_secret: 97defd6bd126d5ba7fa5f296595f82eac905d5eda270207a580ab7c0cb9e8eab
      docker:
        zabbix_agent_docker: True

scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - create
    - prepare
    - converge
    - verify
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
